<Project>
  <PropertyGroup>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**;$(MSBuildProjectDirectory)\artifacts\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="artifacts\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="artifacts\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="artifacts\**\*" />
  </ItemGroup>
</Project>
