using System.Text;
using InfraAgent.Core.Context;
using InfraAgent.Core.Intent;

namespace InfraAgent.Core.Generation;

public sealed class TemplateTerraformGenerator : ITerraformGenerator
{
    public Task<GeneratedTerraform> GenerateAsync(
        InfrastructureIntent intent,
        IReadOnlyList<ContextDocument> context,
        string? repairInstructions,
        CancellationToken cancellationToken)
    {
        var files = new Dictionary<string, string>
        {
            ["provider.tf"] = BuildProvider(intent),
            ["main.tf"] = BuildMain(intent),
            ["variables.tf"] = string.Empty,
            ["outputs.tf"] = BuildOutputs(intent),
            ["terraform.tfvars"] = string.Empty,
            ["README.md"] = "# Generated by InfraAgent\n"
        };

        return Task.FromResult(new GeneratedTerraform(files, BuildSummary(intent), intent.Assumptions));
    }

    private static string BuildProvider(InfrastructureIntent intent) =>
        $$"""
        terraform {
          required_providers {
            aws = {
              source  = "hashicorp/aws"
              version = "~> 5.0"
            }
          }
        }

        provider "aws" {
          region = "{{intent.AwsRegion}}"
        }
        """;

    private static string BuildMain(InfrastructureIntent intent)
    {
        var builder = new StringBuilder();

        if (intent.S3Bucket is { } bucket)
        {
            builder.AppendLine($$"""
            resource "aws_s3_bucket" "uploads" {
              bucket = "{{bucket.BucketName}}"
            }

            """);

            if (bucket.VersioningEnabled)
            {
                builder.AppendLine("""
                resource "aws_s3_bucket_versioning" "uploads" {
                  bucket = aws_s3_bucket.uploads.id

                  versioning_configuration {
                    status = "Enabled"
                  }
                }

                """);
            }

            if (bucket.ServerSideEncryptionEnabled)
            {
                builder.AppendLine($$"""
                resource "aws_s3_bucket_server_side_encryption_configuration" "uploads" {
                  bucket = aws_s3_bucket.uploads.id

                  rule {
                    apply_server_side_encryption_by_default {
                      sse_algorithm = "{{bucket.EncryptionAlgorithm}}"
                    }
                  }
                }

                """);
            }

            if (bucket.BlockPublicAccess)
            {
                builder.AppendLine("""
                resource "aws_s3_bucket_public_access_block" "uploads" {
                  bucket                  = aws_s3_bucket.uploads.id
                  block_public_acls       = true
                  block_public_policy     = true
                  ignore_public_acls      = true
                  restrict_public_buckets = true
                }

                """);
            }
        }

        if (intent.Ec2Instance is { } instance)
        {
            builder.AppendLine($$"""
            data "aws_ami" "amazon_linux" {
              most_recent = true
              owners      = ["amazon"]

              filter {
                name   = "name"
                values = ["{{instance.AmiNamePattern}}"]
              }
            }

            resource "aws_security_group" "web" {
              name        = "{{instance.LogicalName}}-sg"
              description = "Security group generated by InfraAgent"
            """);

            foreach (var rule in instance.IngressRules)
            {
                builder.AppendLine($$"""

              ingress {
                description = "{{rule.Description}}"
                from_port   = {{rule.FromPort}}
                to_port     = {{rule.ToPort}}
                protocol    = "{{rule.Protocol}}"
                cidr_blocks = ["{{rule.CidrBlock}}"]
              }
            """);
            }

            builder.AppendLine("""

              egress {
                from_port   = 0
                to_port     = 0
                protocol    = "-1"
                cidr_blocks = ["0.0.0.0/0"]
              }
            }

            """);

            builder.AppendLine($$"""
            resource "aws_instance" "web" {
              ami                    = data.aws_ami.amazon_linux.id
              instance_type          = "{{instance.InstanceType}}"
              vpc_security_group_ids = [aws_security_group.web.id]

              tags = {
                Name = "{{instance.InstanceName}}"
              }
            }
            """);
        }

        return builder.ToString();
    }

    private static string BuildOutputs(InfrastructureIntent intent)
    {
        var builder = new StringBuilder();

        if (intent.S3Bucket is not null)
        {
            builder.AppendLine("""
            output "s3_bucket_name" {
              value = aws_s3_bucket.uploads.bucket
            }

            """);
        }

        if (intent.Ec2Instance is not null)
        {
            builder.AppendLine("""
            output "ec2_instance_id" {
              value = aws_instance.web.id
            }
            """);
        }

        return builder.ToString();
    }

    private static string BuildSummary(InfrastructureIntent intent)
    {
        var resources = string.Join(" and ", intent.ResourceKinds);
        return $"Generated Terraform for {resources}.";
    }
}
